---
- name: ADD USER TO HOSTS
  hosts: servers
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - vault.yml
#  vars:
#    ansible_become_password: "{{ ansible_become_pass }}" # VAULT
#    user_password: "{{ user_password_plain | password_hash('sha512') }}" # VAULT
  roles:
    - user
