name: Ansible Lint and Test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and linters
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Run Ansible Lint
        run: |
          ansible-lint playbooks/*.yml roles/*/tasks/*.yml

      - name: Run YAML Lint
        run: |
          yamllint .

  test:
    name: Ansible Playbook Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook playbooks/add_user.yml -i inventory/hosts --check --diff
